//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Hospital.Client.RegistrationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDto", Namespace="http://schemas.datacontract.org/2004/07/E_Hospital.BLL.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(E_Hospital.Client.RegistrationService.PatientDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(E_Hospital.Client.RegistrationService.DoctorDto))]
    public partial class UserDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private E_Hospital.Client.RegistrationService.UserRoles RoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public E_Hospital.Client.RegistrationService.UserRoles Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientDto", Namespace="http://schemas.datacontract.org/2004/07/E_Hospital.BLL.Data")]
    [System.SerializableAttribute()]
    public partial class PatientDto : E_Hospital.Client.RegistrationService.UserDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MedicalCardField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalCard {
            get {
                return this.MedicalCardField;
            }
            set {
                if ((object.ReferenceEquals(this.MedicalCardField, value) != true)) {
                    this.MedicalCardField = value;
                    this.RaisePropertyChanged("MedicalCard");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DoctorDto", Namespace="http://schemas.datacontract.org/2004/07/E_Hospital.BLL.Data")]
    [System.SerializableAttribute()]
    public partial class DoctorDto : E_Hospital.Client.RegistrationService.UserDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecializationNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecializationName {
            get {
                return this.SpecializationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecializationNameField, value) != true)) {
                    this.SpecializationNameField = value;
                    this.RaisePropertyChanged("SpecializationName");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRoles", Namespace="http://schemas.datacontract.org/2004/07/E_Hospital.BLL.Data")]
    public enum UserRoles : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Doctor = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Patient = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegistrationService.IRegistrationService")]
    public interface IRegistrationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/RegisterDoctor", ReplyAction="http://tempuri.org/IRegistrationService/RegisterDoctorResponse")]
        bool RegisterDoctor(E_Hospital.Client.RegistrationService.DoctorDto doctor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/RegisterDoctor", ReplyAction="http://tempuri.org/IRegistrationService/RegisterDoctorResponse")]
        System.Threading.Tasks.Task<bool> RegisterDoctorAsync(E_Hospital.Client.RegistrationService.DoctorDto doctor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/RegisterPatient", ReplyAction="http://tempuri.org/IRegistrationService/RegisterPatientResponse")]
        bool RegisterPatient(E_Hospital.Client.RegistrationService.PatientDto patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/RegisterPatient", ReplyAction="http://tempuri.org/IRegistrationService/RegisterPatientResponse")]
        System.Threading.Tasks.Task<bool> RegisterPatientAsync(E_Hospital.Client.RegistrationService.PatientDto patient);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistrationServiceChannel : E_Hospital.Client.RegistrationService.IRegistrationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrationServiceClient : System.ServiceModel.ClientBase<E_Hospital.Client.RegistrationService.IRegistrationService>, E_Hospital.Client.RegistrationService.IRegistrationService {
        
        public RegistrationServiceClient() {
        }
        
        public RegistrationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegisterDoctor(E_Hospital.Client.RegistrationService.DoctorDto doctor) {
            return base.Channel.RegisterDoctor(doctor);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterDoctorAsync(E_Hospital.Client.RegistrationService.DoctorDto doctor) {
            return base.Channel.RegisterDoctorAsync(doctor);
        }
        
        public bool RegisterPatient(E_Hospital.Client.RegistrationService.PatientDto patient) {
            return base.Channel.RegisterPatient(patient);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterPatientAsync(E_Hospital.Client.RegistrationService.PatientDto patient) {
            return base.Channel.RegisterPatientAsync(patient);
        }
    }
}
